# Site settings
title: Daniel Rayneau-Kirkhope
email: daniel.rayneau-kirkhope@aalto.fi
description: ""#>  this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rayneau-kirkhope.co.uk" # the base hostname & protocol for your site
github_username:  danielrayneau-kirkhope
# exclude from generating co-authors
my_authortag: Daniel

# collections
collections:
    papers:
        output: true

# Build settings
markdown: kramdown
